name: book-recommender
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.15
  - pip
  - bottleneck
  - requests               # For making HTTP requests to APIs
  - beautifulsoup4         # For web scraping
  - lxml                   # For parsing XML/HTML (useful with BeautifulSoup) 
  - pip:
      - numpy==1.23.5
      - pandas==1.5.2
      - ipykernel==6.17.1
      - ipython==8.7.0
      - jupyter-client==7.4.7
      - jupyter-core==5.1.0
      - matplotlib==3.6.2
      - python-dotenv      # For loading environment variables from .env file
      - scikit-learn       # For building recommendation models